// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qNWqpef2mCvTAsHXLMc9BA
// Component: 1OQ-ljilqK
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_blank_project.module.css"; // plasmic-import: qNWqpef2mCvTAsHXLMc9BA/projectcss
import * as sty from "./PlasmicWatchlistLabel.module.css"; // plasmic-import: 1OQ-ljilqK/css
import Icon3Icon from "./icons/PlasmicIcon__Icon3"; // plasmic-import: tToAVoz8xc/icon

export const PlasmicWatchlistLabel__VariantProps = new Array();

export const PlasmicWatchlistLabel__ArgProps = new Array();

function PlasmicWatchlistLabel__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props;
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <Icon3Icon
        data-plasmic-name={"svg"}
        data-plasmic-override={overrides.svg}
        className={classNames(defaultcss.all, sty.svg)}
        role={"img"}
      />
    </div>
  );
}

const PlasmicDescendants = {
  root: ["root", "svg"],
  svg: ["svg"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWatchlistLabel__ArgProps,
      internalVariantPropNames: PlasmicWatchlistLabel__VariantProps
    });

    return PlasmicWatchlistLabel__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicWatchlistLabel";
  } else {
    func.displayName = `PlasmicWatchlistLabel.${nodeName}`;
  }
  return func;
}

export const PlasmicWatchlistLabel = Object.assign(
  // Top-level PlasmicWatchlistLabel renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    svg: makeNodeComponent("svg"),
    // Metadata about props expected for PlasmicWatchlistLabel
    internalVariantProps: PlasmicWatchlistLabel__VariantProps,
    internalArgProps: PlasmicWatchlistLabel__ArgProps
  }
);

export default PlasmicWatchlistLabel;
/* prettier-ignore-end */
